### ISSUE TITLE
Title mismatches at readAll activity

### ISSUE THREAD

**Issue by Chromicle** [amfoss/TempleApp#107]
**Describe the bug**
In ReadAll activity, while fetching data if we want to fetch both paid and not paid so while showing list view heading does not match

**To Reproduce**
1. Go to ReadAll activity
2. Click on both paid and not paid and readAll
3. observe at the top 

**Smartphone (please complete the following information):**
 - Device: Samsung j8
 - OS: Android 9 Pie

**Would you like to work on the issue?** (Yes/No)
No

**Comment by hridyakrishna** [comment]
Hello, I would like to work on this issue
