### ISSUE TITLE
Refactor the app code.

### ISSUE THREAD

**Issue by yashk2000** [amfoss/TempleApp#114]
**Describe the chore**
The language/grammar being used in the app needs to be refactored. Almost all sentences currently end with "only". This is one of the issues that need fixing. Refactor any other grammatically wrong strings in the app too.

**Would you like to work on the issue?** (Yes/No)
No

**Comment by athiranair2000** [comment]
Hi,can I work on this issue?

**Comment by ShivangiSingh17** [comment]
Yeah sure @athiranair2000 !
