### ISSUE TITLE
It will be better to restrict user to add either "user ID" or "name", without leaving both details empty

### ISSUE THREAD

**Issue by mustaqmustu** [amfoss/TempleApp#12]
**Describe the bug**
At present, user is allowed to submit details without filling both user Id and name.It will be better to restrict user to add either "user ID" or "name", without leaving both empty.

**Screenshots**

![ezgif com-video-to-gif(14)](https://user-images.githubusercontent.com/43813438/59024833-67c21c80-8870-11e9-8a50-cfc620495a22.gif)

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by yashk2000** [comment]
@mustaqmustu good idea. Make it compulsory for the user to insert user name..it's fine if a name is not there, but user name should be there. 
Also please mention whether you'll like to work on the issue or not.
