### ISSUE TITLE
Integrate Travis CI

### ISSUE THREAD

**Issue by aswinshenoy** [amfoss/TempleApp#14]
**Describe the chore**
Integrate Travis CI

https://docs.travis-ci.com/user/languages/android/
https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4

**Would you like to work on the issue?**
- [ ] Yes
- [x] No

**Comment by Chromicle** [comment]
@aswinshenoy thanks for raising issue @ShivangiSingh17 wants to work on this issue
