### ISSUE TITLE
Change Issue Template of the Repository.

### ISSUE THREAD

**Issue by aswinshenoy** [amfoss/TempleApp#15]
**Describe the chore**
The "Yes"/"No" is recognized as a checklist by Github. So, selecting one will show in the issues as "1 of 2 completed", which is not something that was meant.
![image](https://user-images.githubusercontent.com/21276922/59029949-3bf96380-887d-11e9-992f-abb8089c6faf.png)

**Comment by yashk2000** [comment]
This happens in case the checklist was in the pull request template. Currently, this thing isn't in a problem in the issue template.

**Comment by yashk2000** [comment]
That isn't much of a problem according to me. But we'll find an alternative to this.

**Comment by yashk2000** [comment]
@aswinshenoy done.
