### ISSUE TITLE
Data  Binding

### ISSUE THREAD

**Issue by abhijitramesh** [amfoss/TempleApp#20]
**Describe the chore**
Currently the app is using the normal findViewById for linking the UI with the methods this will sometimes result in crashes and poor performing apps. It would be really nice if Butter Knife Library by Jake Wharton is used for View Binding

**Would you like to work on the issue?** (Yes/No)
No

**Comment by immadisairaj** [comment]
Change this issue to use [Data Binding](https://developer.android.com/topic/libraries/data-binding#java)
