### ISSUE TITLE
Use Proper Annotations and Comments

### ISSUE THREAD

**Issue by abhijitramesh** [amfoss/TempleApp#21]
**Describe the chore**
In some places comments are given without proper annotations
eg:
TempleApp/src/main/java/example/TempleApp/Activities/MainActivity.java

The comment given is:
``` java
/**
 * Created by Chromicle.
 */
```
Where it should be 
``` java
/**
 * @author Chromicle
 */
```

**Would you like to work on the issue?** (Yes/No)
No

**Comment by abhinandhari** [comment]
May I help in addressing this issue?

**Comment by vchrombie** [comment]
@abhinandhari 
Yes, sure.

Feel free to ask if you have any doubts. :slightly_smiling_face: 
Looking forward to your PR.
