### ISSUE TITLE
Remove Hardcoded Strings and Texts

### ISSUE THREAD

**Issue by abhijitramesh** [amfoss/TempleApp#22]
**Describe the chore**
There are about 84 Hard coded Strings and 30 Hard coded text in the whole project it would be really nice if these resources are extracted.

**Would you like to work on the issue?** (Yes/No)
No

**Screenshots**

![Screenshot from 2019-06-10 20-35-34](https://user-images.githubusercontent.com/43090559/59205020-894c3c80-8bbf-11e9-8141-20db19157a7c.png)
![Screenshot from 2019-06-10 20-36-01](https://user-images.githubusercontent.com/43090559/59205026-8bae9680-8bbf-11e9-9e5c-aede4ab1e65c.png)

**Comment by adarshsiva** [comment]
Can I work on the issue?

**Comment by Chromicle** [comment]
Yeah proceed

**Comment by vchrombie** [comment]
@adarshsiva 
We would definitely like to see new people contributing to the project. Feel free to ask if you have any doubts. :slightly_smiling_face: 

Looking forward to your PR.
