### ISSUE TITLE
Rename the app package.

### ISSUE THREAD

**Issue by yashk2000** [amfoss/TempleApp#32]
**Describe the feature you'd like**
Currently, the app package is `com.example.TempleApp`. Rename it to `org.amfoss.TempleApp` and made any other changes required for this.

**Would you like to work on the issue?** (Yes/No)
No.

**Comment by immadisairaj** [comment]
@yash2000 I think it has to be renamed to
com.amfoss.temple.app or com.amfoss.templeapp.

**Comment by yashk2000** [comment]
Yeah. `com.amfoss.templeapp` will do :)

**Comment by athiranair2000** [comment]
Can I work on this issue?

**Comment by yashk2000** [comment]
@athiranair2000 sure. Go ahead :)
Rename it to `org.amfoss.templeapp`

**Comment by abhijitramesh** [comment]
Shall I work on this issue?
