### ISSUE TITLE
Inserting wrong ID

### ISSUE THREAD

**Issue by Chromicle** [amfoss/TempleApp#49]
**Describe the bug**
When we insert values once again instead of coming back to the main activity then the `username` is not inserted in the correct way.

##### ex:
First time: `hello`
Second time: `hellohello`
Third time: `hellohellohello`

**To Reproduce**
1. Go to `insert_activity`
2. Insert any values 
3. Instead of coming back to main activity insert once again
4. See the database
5. Observe the error

**Expected behavior**
Inserting new values should happen properly.

**Smartphone (please complete the following information):**
 - Device: Samsung J8
 - OS:  Android 9 Pie

**Would you like to work on the issue?** (Yes/No)
No

**Comment by athiranair2000** [comment]
I would like to work on this issue. Shall I proceed?

**Comment by ShivangiSingh17** [comment]
I would like to work on this issue. Shall I ?

**Comment by yashk2000** [comment]
Sure proceed with it :smile:
