### ISSUE TITLE
Add an apk branch

### ISSUE THREAD

**Issue by yashk2000** [amfoss/TempleApp#54]
**Describe the chore**
Add an apk branch so that anyone can download the apk and test the app without building it using the Android Studio. 

**Would you like to work on the issue?** (Yes/No)
YES.

**Comment by AnoopkRajan** [comment]
If this issue is available can i work on it?

**Comment by yashk2000** [comment]
Sure @AnoopkRajan. Go ahead :)

**Comment by vchrombie** [comment]
@yashk2000, how it would be working?
When this `apk` branch will be updated each time?

**Comment by immadisairaj** [comment]
@AnoopkRajan, @yashk2000 what is the status of this issue?
