### ISSUE TITLE
Replace App icon

### ISSUE THREAD

**Issue by Chromicle** [amfoss/TempleApp#73]
**Describe the feature you'd like**
Currently, the icon we are using is a google search result image, hence might have copyright issues.

**Additional context**
If anyone is willing to make a new icon, upload the image here in the comments sections for everyone to review and provide opinions.

**Comment by Chromicle** [comment]
<img src="https://user-images.githubusercontent.com/48018942/60723525-7aa03d80-9f51-11e9-8bed-3c6a6583feb1.png" height = "150" width="150">

**Comment by immadisairaj** [comment]
@Chromicle did you make it? or took it from somewhere

**Comment by immadisairaj** [comment]
@Chromicle any update on this issue?

**Comment by yashk2000** [comment]
@Chromicle any ideas for this?
