### ISSUE TITLE
Displaying non-functioning editTexts

### ISSUE THREAD

**Issue by Chromicle** [amfoss/TempleApp#75]
**Describe the bug**
Currently, when we inserting donations, there are 2 non-functioning edit texts with hints as `customPooja` and `amount`. Hide them when we insert a new donation.

**To Reproduce**
1. Go to InsertActivty
2. Select Donations
3. Scroll down'
4. 2 non-functioning editTexts can be seen.

**Expected behavior**
editTexts should be hidden when we are inserting donations.

**Screenshots**

![Screenshot_20190708-205102_TempleApp](https://user-images.githubusercontent.com/48018942/60823003-2f419580-a1c4-11e9-9957-0afcba7a7462.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung J8
 - OS: 9 Pie

**Would you like to work on the issue?** (Yes/No)
No

**Comment by adarshsiva** [comment]
Can i work on this?
