### ISSUE TITLE
The UI is not proper while viewing all donations/pooja

### ISSUE THREAD

**Issue by immadisairaj** [amfoss/TempleApp#76]
**Describe the bug**
At the side in the view of all donations/pooja the UI is no proper

**To Reproduce**
1. Click View All Pooja/Donation
2. Check Registered Poojas
3. The UI is not proper

**Expected behavior**
The UI should be clear

**Screenshots**

![Screenshot_20190709_182053](https://user-images.githubusercontent.com/40348358/60889397-89029800-a276-11e9-96e9-f18e7976e4c3.jpg)

**Smartphone (please complete the following information):**
 - Device: Vivo V5s
 - OS: Android 7

**Would you like to work on the issue?** 
No

**Comment by Chromicle** [comment]
Note: In some of the devices like Samsung J8 it is working properly 
please check on multiple devices before sending PR
