### ISSUE TITLE
Toast messages are displayed for a very long time

### ISSUE THREAD

**Issue by ShivangiSingh17** [amfoss/TempleApp#79]
**Describe the bug**
The toast messages under all section are displayed for a very long time.

**To Reproduce**
Select any section from the home screen and observe that the toast message appears at the bottom of the screen for a very long time.

**Expected behaviour**
The toast message should be displayed for a shorter duration.

**Comment by adarshsiva** [comment]
Can I work on this?

**Comment by Chromicle** [comment]
> Can I work on this?

yeah, proceed :small_airplane:

**Comment by AnoopkRajan** [comment]
Is this issue fixed?
If not can i work on it?

**Comment by Chromicle** [comment]
> Is this issue fixed?
> If not can i work on it?
@AnoopkRajan  it is free to work please proceed :small_airplane: 
Looking forward to your PR

**Comment by AnoopkRajan** [comment]
I have fixed this issue . Can i push it?

**Comment by AjithKalarikal** [comment]
I fixed it and pushed the code.Is that okay?_

**Comment by yashk2000** [comment]
@AjithKalarikal please close your pr. This issue has been assigned to @AnoopkRajan. If he is not working on it any longer, then only work on it.

**Comment by yashk2000** [comment]
@AnoopkRajan if you have fixed the issue, please create a pr with proper format.

**Comment by AnoopkRajan** [comment]
@yashk2000  I have fixed the issue but there is a new  issue with Travis Build . 
Trying to fix the issue thoroughly.

**Comment by yashk2000** [comment]
@AnoopkRajan great. Do ensure that travis build passes :)

**Comment by AnoopkRajan** [comment]
@yashk2000 
Thanks for the response.
Working on the build.

**Comment by AnoopkRajan** [comment]
Have completed the issue with all the requested changes .
Looking forward for review or merge .

**Comment by AnoopkRajan** [comment]
Have fixed the toast duration issue with all the requested changed addressed .
Looking forward for review or merge.
