### ISSUE TITLE
Restrict editTexts to take numbers only as input for Amount

### ISSUE THREAD

**Issue by Chromicle** [amfoss/TempleApp#81]
**Describe the bug**
Currently, edit texts for amount of money donated is accepting all type of texts restrict them to take input only numbers 

**Expected behavior**
EditTexts should take only numbers as inputs 

**Smartphone (please complete the following information):**
 - Device: Samsung j8
 - OS: Android 9 pie

**Additional context**
Please update in all activities
Make editTexts view with keyboard number only

**Would you like to work on the issue?** (Yes/No)
No

**Comment by yashk2000** [comment]
@adarshsiva this task is yourrs.

**Comment by adarshsiva** [comment]
ok
