### ISSUE TITLE
Edit toast messages in Search section

### ISSUE THREAD

**Issue by mustaqmustu** [amfoss/TempleApp#90]
**Describe the bug**
When user clicks on "people who registered "in search section, wrong toast is appearing as"Selected to register pooja". It is repeating with "People who Donated money".

**Expected behavior**
A clear toast message.

**Screenshots**
![image](https://user-images.githubusercontent.com/43813438/62374593-ef1eca00-b559-11e9-972a-c2044e376819.png)
![image](https://user-images.githubusercontent.com/43813438/62374601-f3e37e00-b559-11e9-97db-2967814c4b2a.png)

**Would you like to work on the issue?** (Yes/No)
No.

**Comment by Chromicle** [comment]
@mustaqmustu thank you for reporting a valid issue :tada:

**Comment by bharathspi** [comment]
can I work on it?

**Comment by Chromicle** [comment]
@bharathspi yeah proceed :+1:

**Comment by gopikaharikumar** [comment]
I would like to work on this issue
