### ISSUE TITLE
Make mockup for Improvising UI

### ISSUE THREAD

**Issue by abhijitramesh** [amfoss/TempleApp#96]
**Describe the chore**
Currently the UI is not much user friendly so It has to be made made in such a way that the targeted audience can use them without any learning curve, to achieve this we need a proper mockup.
**Would you like to work on the issue?** (Yes/No)
No

**Comment by vaishnav04** [comment]
May I work on this?

**Comment by abhijitramesh** [comment]
@vaishnav04 Yes you can work on this issue

**Comment by yashk2000** [comment]
@vaishnav04 thanks a lot. We really appreciate you taking time to fix this issue :smile:

**Comment by vaishnav04** [comment]
@yashk2000 will get them done asap :)

**Comment by padth4i** [comment]
Here is the link to the mockups
 https://xd.adobe.com/spec/f4a98c6f-d6f6-4eae-5744-047ad958b58b-8298/

**Comment by immadisairaj** [comment]
Good work @vaishnav04  👍 🥇
