### ISSUE TITLE
Select pooja type appears on donate money to temple

### ISSUE THREAD

**Issue by abhijitramesh** [amfoss/TempleApp#99]
**Describe the bug**

Select pooja type text is appearing on clicking Donate money to temple.

**To Reproduce**

* Click on Add pooja/donation
* Click on Donate Money to Temple

**Expected behavior**
Select pooja type text should not be there

**Screenshots**
![photo_2019-08-07_22-02-52](https://user-images.githubusercontent.com/43090559/62640431-3264a880-b95f-11e9-94d7-5978693f3e17.jpg)

**Smartphone**
 - Device: OnePlus6t Mclaren
 - OS: Android 9 Pie

**Would you like to work on the issue?** (Yes/No)
No

**Comment by bharathspi** [comment]
I would like to work on it.

**Comment by abhijitramesh** [comment]
Sure @bharathspi you can work on this issue

**Comment by yashk2000** [comment]
@bharathspi will you be working on this issue?

**Comment by yashk2000** [comment]
I'm un-assigning the issue from @bharathspi since he is not responding.

**Comment by athiranair2000** [comment]
Shall I work on this issue?

**Comment by Chromicle** [comment]
@athiranair2000 yeah proceed
